local/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/* Rutas Frontend */ 
// Rutas de las paginas Informativas
	Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
	//Route::get('/', 'Frontend\PaginasController@index')->name('inicio');
	Route::get('/categoria/{id}', 'Frontend\PaginasController@categoria');
	Route::get('/producto/{id}', 'Frontend\PaginasController@producto');
	Route::post('/mostrardatosproducto',	'Frontend\PaginasController@mostrardatosproducto')->name('producto.mostrardatosproducto');
	Route::get('/quienes-somos', 'Frontend\PaginasController@empresa');
	Route::get('/nuestros-clientes', 'Frontend\PaginasController@nuestrosClientes');
	Route::get('/servicios', 'Frontend\PaginasController@servicios');
	Route::get('/productos', 'Frontend\PaginasController@productos');
	Route::get('/noticias', 'Frontend\PaginasController@noticias');
	Route::get('/noticias/{slug}', 'Frontend\PaginasController@articulo');
	Route::get('/certificaciones', 'Frontend\PaginasController@certificaciones');
	Route::get('/contactos', 'Frontend\PaginasController@contactos');
	Route::get('/productos/{id}', 'Frontend\PaginasController@producto');
	Route::post('/enviarmensaje',	'Frontend\PaginasController@enviarmensaje')->name('paginas.enviarmensaje');
// Fin de las rutas de las paginas informativas

// Carrito de compra
	Route::resource('cart', 'Frontend\CartsController');
	Route::post('cart/addProducto/{id}', 'Frontend\CartsController@addProducto');
	Route::post('cart/guardarPedido', 'Frontend\CartsController@guardarPedido');
	Route::post('cart/ingresar-pago', 'Frontend\CartsController@pagos');
	Route::post('save-deposito', 'Frontend\CartsController@subirDocumento');
// Fin carrito

// Lista de deseados
	Route::resource('wishlist', 'Frontend\WishlistController');
// Fin lista de deseados

// Rutas para los Cliente
	Route::prefix('cliente')->group(function () {

// Rutas de login de los clientes 
	Route::get('login', 'Auth\ClienteLoginController@login')->name('cliente.auth.login');
	Route::post('login', 'Auth\ClienteLoginController@loginCliente')->name('cliente.auth.loginCliente');
	Route::post('logout', 'Auth\ClienteLoginController@logout')->name('cliente.auth.logout');

	Route::get('redirect/{provider}', 'Auth\ClienteLoginController@redirectToProvider')->name('loginSocial');
	Route::get('callback/{provider}', 'Auth\ClienteLoginController@handleProviderCallback');
// Fin de rutas de login clientes

// Panel de adminstraccion del cliente
	Route::get('/', 'Frontend\ClienteController@index')->name('cliente.dashboard');
	Route::get('dashboard', 'Frontend\ClienteController@index')->name('cliente.dashboard');
	Route::get('mis-pedidos', 'Frontend\ClienteController@misPedidos')->name('cliente.misPedidos');
	Route::post('cancelar-pedido', 'Frontend\ClienteController@cancelarPedido');
	Route::get('ofertas', 'Frontend\ClienteController@ofertas')->name('cliente.getOfertas');
	Route::get('deseados', 'Frontend\ClienteController@deseados')->name('cliente.misDeseos');
	Route::get('miperfil', 'Frontend\ClienteController@miPerfil')->name('cliente.miPerfil');
	Route::post('actualizar-perfil', 'Frontend\ClienteController@guardarPerfil');
	Route::post('save-direccion', 'Frontend\ClienteController@guardarDireccion');
	Route::get('show-direccion/{id}', 'Frontend\ClienteController@mostrarDireccion');
	Route::get('delete-direccion/{id}', 'Frontend\ClienteController@eliminarDireccion');
	Route::get('register', 'Frontend\ClienteController@create')->name('cliente.register');
	Route::post('register', 'Frontend\ClienteController@store')->name('cliente.register.store');
// Fin del panel de adminstracion del cliente

// Rutas para el pago de compra  
	Route::get('saveCard', 'Frontend\CartsController@saveCard')->name('saveCard');
	Route::get('checkout/{id}', 'Frontend\CartsController@formPago')->name('checkout');
	Route::post('checkout-save', 'Frontend\CartsController@formSave')->name('checkoutSave');
	Route::get('pagar-pedido/{id}', 'Frontend\CartsController@pagar');
	Route::get('estado-pago/{code}/{orden}', 'Frontend\CartsController@estadoPago');
	Route::get('getcupon/{id}/{cupon}','Frontend\CartsController@agregarCupon');
// Fin del carrito de comprar

// Rutas para recuperar contraseña
	Route::get('password/reset', 'Auth\ClienteForgotPasswordController@showLinkRequestForm')->name('cliente.password.request');
	Route::post('password/email', 'Auth\ClienteForgotPasswordController@sendResetLinkEmail')->name('cliente.password.email');

});
// Fin de rutas clientes
/* Fin Rutas Frontend */



/* Inicio Backend */

// Rutas de login Administrador
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');

// Password Reset Routes Administrador
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::group(['middleware' => ['auth']], function(){

	Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

	// Rutas inicialiales
	Route::get('/home', 'Backend\HomeController@index')->name('home');
	Route::get('/administracion', 'Backend\BackendController@index');
	// fin de las rutas iniciales

	// Inicio de adminsitracion de usuaruios
	Route::resource('usuarios','Backend\UsuariosController');
	Route::get('/perfil', 'Backend\UsuariosController@perfil')->name('perfil');
	Route::resource('tipos-usuarios','Backend\TiposController');
	Route::resource('menu', 'Backend\MenuController');
	Route::resource('permisos', 'Backend\PermisoController');
	// Fin de administracion de usuarios 

	// Inicio de administracion de clientes
	Route::resource('clientes', 'Backend\ClientesController');
	Route::get('saldo-cliente', 'Backend\ClientesController@saldoCliente');
	Route::resource('menu-pagina', 'Backend\MenuPaginaController');
	// fin administracion de clientes

	// Inicio  de administracion de contenido
	Route::resource('articulos', 'Backend\ArticulosController');
	Route::post('/upload', 'Backend\ArticulosController@subirfotogaleria');
	Route::post('/uploaddoc', 'Backend\ArticulosController@subirdoc');
	Route::get('/activaciones','Backend\ArticulosController@activaciones');
	Route::post('/activararticulo/{id}', 'Backend\ArticulosController@habilitArarticulo')->name('hab_articulo');
	Route::resource('categorias','Backend\CategoriasController');
	Route::resource('tags', 'Backend\TagsController');
	Route::post('/getTags/{id}', 'Backend\TagsController@getTagsByCategoria');
	// Fin de adminsitracion de contenido

	// Administracion de carrito
		Route::resource('carrito', 'Backend\CarritoController');
		Route::post('carrito/save-politica', 'Backend\CarritoController@subirDocumento');
		Route::resource('cupones','Backend\CuponController');
		Route::resource('pedidos', 'Backend\PedidosController');
		Route::resource('depositos', 'Backend\DepositosController');
	// Fin administracion de carrito

	// Administracion Productos
		Route::resource('shop','Backend\TiendaController');
		Route::post('/upfoto', 'Backend\TiendaController@subirfotogaleria');
		Route::resource('categoriaproductos','Backend\CategoriaproductosController');
		Route::post('/getCproductos/{id}', 'Backend\CategoriaproductosController@getCproductos');
	// Fin administracion de productos	

	//Inicio Modulos
		Route::resource('categoriainterna','Backend\CategoriaInternaController');
		Route::resource('animacion', 'Backend\SliderController');
		Route::resource('imagen', 'Backend\ImagenesController');
		Route::resource('video', 'Backend\VideoController');
	//Fin Modulos

	// Rutas Administracion
		Route::resource('/informacion', 'Backend\InformacionController');
		Route::resource('configuracion', 'Backend\ConfiguracionController');
	// Fin Rutas administracion

	// Inicio de campos extras
		Route::resource('camposextrasgrupos','Backend\CamposExtrasGruposController');
		Route::resource('camposextras','Backend\CamposExtrasController');
	// Fin Campos extras 

	// Inicio cursos
		Route::resource('cursos', 'Backend\CursosController');
		Route::post('cursos/filtrar', 'Backend\CursosController@filtrar');
		Route::get('modulos-articulo/{id}', 'Backend\CursosController@ModulosArticulo');

		Route::resource('modulo', 'Backend\ModuloController');
	// Fin cursos 

	// Inicio documentos
		Route::post('upload-image', 'UploadController@upload_image');
		Route::post('upload-file', 'UploadController@upload_file');
	// Fin documentos

	// Rutas que no se usan
	Route::resource('galeria', 'FotosController');
	Route::resource('especificaciones', 'EspecificacionController');
	//Route::post('/enviarconsulta',	'Frontend\PaginasController@enviarconsulta')->name('paginas.enviarconsulta');
	//Route::get('/etiqueta/{tag}',	'Frontend\PaginasController@tags')->name('Tags');
	//Route::get('/galeria/{slug}',	'Frontend\PaginasController@galeria')->name('galeria');
	//Route::get('/infoevento', 		'Frontend\PaginasController@infoeventos');
	//Route::get('/proyectos/{slug}', 'Frontend\PaginasController@articulo')->name('proyectos.slug');
	//Route::get('/email', 			'Frontend\PaginasController@email')->name('email');
	//Route::get('/apinoticia',		'ApiNoticiasController@api')->name('apinoticia');
	//Antiguo FUNCIONA Route::get('/noticia', 'ApiNoticiasController@noticia')->name('noticia');	

});

local/app/Articulo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
// use Cviebrock\EloquentSluggable\SluggableInterface;
// use Cviebrock\EloquentSluggable\SluggableTrait;

// class Articulo extends Model implements SluggableInterface
class Articulo extends Model
{

    // use SluggableTrait;

    // protected $sluggable = [
    //     'build_from' => 'titulo',
    //     'save_to'    => 'slug',
    // ];


    //
  protected $table = 'articulos';

  protected $fillable = ['longitud','latitud','titulo', 'slug', 'texto','id_categoria', 'activado', 'destacado',  'path',  'rutadoc','id_usuario', 'seo_keyword', 'seo_descripcion','fechainicio','fechafin','lugar','id_prioridad','descripcionredes'];

  protected $hidden = [];



     public function categoria()
    {
        return $this->belongsTo('App\Categoria');
    }
    public function usuario()
    {
        return $this->belongsTo('App\User');
    }

     public function tags()
    {
        return $this->belongsToMany('App\Tag');
    }

    public function articulosFotos()
    {
        return $this->hasMany('App\Foto', 'articulo_id');
    }

    public function articulosVideos()
    {
        return $this->hasMany('App\Videosar', 'id_articulos');
    }
    public function articulosDocumentos()
    {
        return $this->hasMany('App\Documentos', 'articulo_id');
    }


}

local/app/Http/Controllers/activacion.blade.php
<div style="font-family:'Droid Sans',Arial,Verdana;color:#393a3f;font-size:13px;line-height:20px"><div class="adM">
</div><div style="border:5px #eeeeee solid;margin:5px;border-radius:10px;background:#fff;width:615px"><div class="adM">
    </div><div style="background:#eeeeee;padding:10px;width:595px"><div class="adM">
        </div><img src="http://casasvacacionales.com.ec/assets/img/logo-color-big.png" class="CToWUd">
    </div>
    <div style="padding:10px">
        Usuario/a {{$nombres}} {{$apellidos}},<br>
<br>
¡Gracias por unirte a Casas Vacacionales!<br>
<br>
Informamos que su cuenta ha sido activada por el administrador del sitio.<br>
 <br>
        <br>
        Saludos cordiales,<br>
        <br>
        El equipo Casas de vacaciones<br>
        <a href="http://www.casasdevacaciones.com.ec">http://www.casasdevacaciones.<wbr>com.ec</a><br>
        Correo electrónico: <a href="mailto:soporte@casasdevacaciones.com.mx" target="_blank">info@casasdevacaciones.com.<wbr>ec</a><br>
        Teléfono: 593

        
    </div>
    <div style="color:#929292;font-size:11px;padding:10px 30px;text-align:center">
        <p style="margin:0"></p>
    </div>
</div>
<img src="" style="width:1px;height:1px" alt="" class="CToWUd"></div>

local/resources/views/admin/articulos/activacion.blade.php
@extends('layouts.backend')
@section('titulo')
<div style="display: flex;justify-content: center;align-items: center;">
    <p style="margin-right: 30px; margin-bottom: 0px;">Activaciones de articulos</p>
    <a class="btn btn-primary btn_crear" href="{{ URL::route('articulos.create') }}">Nuevo</a>
</div>
@endsection
@section('contenido')

    @if(Session::has('message'))
        <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {{Session::get('message')}}
        </div>
    @endif
    <!-- <br>
    <a class="btn btn-primary" href="{{ URL::route('articulos.create') }}">Nuevo</a>
    <br> -->
@if (count($articulos))
<br>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            
            <!-- /.box-header -->
            <div class="box-body">
                <table  id="tbbuzon" class="table table-striped table-bordered table-hover display" >
                    <thead>
                        <th>#</th>
                        <th>ID</th>
                        <th>Título</th>
                        <th style="width:30%;">Contenido</th>
                        <th>Autor</th>
                        <th>Categoria</th>
                        <th>Imagen</th>
                        <th>Acciones</th>
                    </thead>
                    <tbody>
                        <tr>
                            <?php $s = 0 ; ?>
                            @foreach ($articulos as $articulo)
                            <td>{{$articulo->id}}</td>
                            <td> <?php $s = $s + 1; echo $s; ?></td>
                            <td>{{$articulo->titulo}}</td>
                            <td><?php $ser1 = substr($articulo->texto,0,200); echo strip_tags($ser1); ?></td>
                            <td>{{$articulo->nombres}}</td>
                            <td>{{$articulo->categoria}}</td>
                            @if(empty($articulo->path))
                            <td><img src="{{asset('assets/images')}}/no-imagen.jpg"  style ="width: 50px; height: 50px!important;object-fit: cover!important;"></td>
                            @else
                            <td>
                                <div class="lightBoxGallery">
                                    <a href="{{asset('local/public/images')}}/{{$articulo->path}}" title="Image from Unsplash" data-gallery="">
                                        <img  style="width: 50px;height: 50px!important;"  src="{{asset('local/public/images')}}/{{$articulo->path}}">
                                    </a>
                                    
                                    
                                    <!-- The Gallery as lightbox dialog, should be a child element of the document body -->
                                    <div id="blueimp-gallery" class="blueimp-gallery">
                                        <div class="slides"></div>
                                        <h3 class="title"></h3>
                                        <a class="prev">‹</a>
                                        <a class="next">›</a>
                                        <a class="close">×</a>
                                        <a class="play-pause"></a>
                                    <ol class="indicator"></ol>
                                </div>
                            </div>
                            
                        </td>
                        @endif
                        <td>
                            {!! Form::open(array('method' => 'POST', 'route' => array('hab_articulo', $articulo->id))) !!}
                                {!! Form::submit('Activar', array('class' => 'btn btn-primary')) !!}
                            {!! Form::close() !!}
                            <a class="btn btn-success" href="{{route('articulos.edit', $articulo->id)}}" role="button">
                                <i class="fa fa-pencil-square-o"></i>
                            </a>
                            <a class="btn btn-danger" href="{{route('articulos.destroy', $articulo->id)}}" onclick="return confirm('Quiere borrar el registro?')" role="button">
                                <i class="fa fa-trash-o"></i>
                            </a>
                            
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            
        </div>
        
    </div>
</div>
</div>
    @else
        <div class="alert alert-success" role="alert">
            No existen articulos por activar
        </div>
    @endif
@endsection

local/resources/views/admin/articulos/index.blade.php
@extends('layouts.backend')

@section('titulo')
<div style="display: flex;justify-content: center;align-items: center;">
    <p style="margin-right: 30px; margin-bottom: 0px;">Artículos</p>
    <a class="btn btn-primary btn_crear" href="{{ URL::route('articulos.create') }}">Nuevo</a>
</div>
@endsection
@section('contenido')

    @if(Session::has('message'))
        <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {{Session::get('message')}}
        </div>
    @endif

    <!-- <br>
    <a class="btn btn-primary" href="{{ URL::route('articulos.create') }}"> <i class="fa fa-plus"></i> Nuevo</a>
    <br> -->

    @if (count($articulos))
    <br>
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-body">
                    <table  id="tbbuzon" class="table table-bordered  text-center table-hover display" >
                        <thead>
                            <th>ID</th>
                            <th style="width:50%;" class="text-left">Título <br> <small class="text-muted">Contenido</small></th>
                            <th>Autor</th>
                            <th>Activado</th>
                            <th>destacado</th>
                            <th>Categoria</th>
                            <th>Imagen</th>
                            <th>Acciones</th>
                        </thead>
                        <tbody>
                            @foreach ($articulos as $articulo)
                            <tr>
                                <td>{{ $articulo->id }}</td>
                                <td class="text-left">
                                    <b>{{ $articulo->titulo }}</b><br>
                                    <small class="text-muted">
                                        {{ strip_tags(substr($articulo->texto,0,150)) }}{{ strlen($articulo->texto) > 150 ? '...' : '' }}
                                    </small>
                                </td>
                                <td>{{ $articulo->nombres }}</td>
                                <td>
                                    @if ($articulo->estado)
                                        <span class="badge badge-primary">SI</span>
                                    @else
                                        <span class="badge badge-warning">NO</span>
                                    @endif
                                </td>
                                <td>
                                    @if ($articulo->destacado)
                                        <span class="badge badge-primary">SI</span>
                                    @else
                                        <span class="badge badge-warning">NO</span>
                                    @endif
                                </td>
                                <td>{{ $articulo->categoria }}</td>
                                <td>
                                @if(empty($articulo->path))
                                    <img src="{{asset('assets/images')}}/no-imagen.jpg" onerror=" this.src = '{{asset('assets/images')}}/articulo.png';" style ="width: 50px; height: 50px!important;object-fit: cover!important;"></td>
                                @else
                                    <div class="lightBoxGallery">
                                        <a href="{{asset('local/public/images')}}/{{$articulo->path}}" title="Image from Unsplash" data-gallery="">
                                            <img  style="width: 50px;height: 50px!important;"  src="{{asset('local/public/images')}}/{{$articulo->path}}" onerror="this.src = '{{asset('assets/images')}}/no-imagen.jpg';" >
                                        </a>
                                        <!-- The Gallery as lightbox dialog, should be a child element of the document body -->
                                        <div id="blueimp-gallery" class="blueimp-gallery">
                                            <div class="slides"></div>
                                            <h3 class="title"></h3>
                                            <a class="prev">‹</a>
                                            <a class="next">›</a>
                                            <a class="close">×</a>
                                            <a class="play-pause"></a>
                                            <ol class="indicator"></ol>
                                        </div>
                                    </div>
                                @endif                            
                                </td>
                                <td>
                                    <a class="btn btn-success" href="{{route('articulos.edit', $articulo->id)}}" role="button">
                                        <i class="fa fa-pencil-square-o"></i>
                                    </a>
                                    {!! Form::open(array('method' => 'DELETE', 'route' => array('articulos.destroy', $articulo->id))) !!}
                                      <button type="submit" onclick="return confirm('Quiere borrar el registro?')" class="btn btn-danger"><span class="fa fa-trash-o"></span></button>
                                    {!! Form::close() !!}
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    @else
        <br>
       <div class="alert alert-warning" role="alert">
            No hay Artículos registrados, comencemos <a href="{{ route('articulos.create') }}" class="alert-link">registrando el primero dando click aqui</a>
        </div>
    @endif

@endsection

@section('script')
    
<script>
    function accents_supr(data){
        return ! data ?
        '' :
        typeof data === 'string' ?
        data
            .replace( /\n/g, ' ' )
            .replace( /[áàäâ]/g, 'a' )
            .replace( /[éèëê]/g, 'e' )
            .replace( /[íìïî]/g, 'i' )
            .replace( /[óòöô]/g, 'o' )
            .replace( /[úùüû]/g, 'u' ):
        data;
        jQuery.extend(jQuery.fn.dataTableExt.oSort, {
            "spanish-string-asc"  : function (s1, s2) { return s1.localeCompare(s2); },
            "spanish-string-desc" : function (s1, s2) { return s2.localeCompare(s1); }
        });

        jQuery.fn.DataTable.ext.type.search['spanish-string'] = function ( data ) {
            return accents_supr(data);
        }
    }

    jQuery.fn.DataTable.ext.type.search.string = function ( data ) {
        return ! data ?
        '' :
        typeof data === 'string' ?
        data
            .replace( /έ/g, 'ε' )
            .replace( /[ύϋΰ]/g, 'υ' )
            .replace( /ό/g, 'ο' )
            .replace( /ώ/g, 'ω' )
            .replace( /ά/g, 'α' )
            .replace( /[ίϊΐ]/g, 'ι' )
            .replace( /ή/g, 'η' )
            .replace( /\n/g, ' ' )
            .replace( /á/g, 'a' )
            .replace( /é/g, 'e' )
            .replace( /í/g, 'i' )
            .replace( /ó/g, 'o' )
            .replace( /ú/g, 'u' )
            .replace( /ê/g, 'e' )
            .replace( /î/g, 'i' )
            .replace( /ô/g, 'o' )
            .replace( /è/g, 'e' )
            .replace( /ï/g, 'i' )
            .replace( /ü/g, 'u' )
            .replace( /ã/g, 'a' )
            .replace( /õ/g, 'o' )
            .replace( /ç/g, 'c' )
            .replace( /ì/g, 'i' ) :
        data;
    };
</script>
@endsection

local/resources/views/admin/articulos/modal.blade.php
<div class="modal fade modal-slide-in-right" aria-hidden="true" role="dialog" tabindex="-1" id="modal-vervideo"  >
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true"></span>
				</button>
				<h4 class="modal-title">Visualizar Video</h4>
			</div>
			<div class="modal-body">
				<p>Eliminar Impresora: </p>
				<div id="reproductor">
					<iframe width='600' height='600' src='https://www.youtube.com/embed/"+videourl+"?rel=0' frameborder='0' allow='autoplay; encrypted-media' allowfullscreen></iframe>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
			</div>
		</div>
	</div>
</div>