local/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/* Rutas Frontend */ 
// Rutas de las paginas Informativas
	Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
	//Route::get('/', 'Frontend\PaginasController@index')->name('inicio');
	Route::get('/categoria/{id}', 'Frontend\PaginasController@categoria');
	Route::get('/producto/{id}', 'Frontend\PaginasController@producto');
	Route::post('/mostrardatosproducto',	'Frontend\PaginasController@mostrardatosproducto')->name('producto.mostrardatosproducto');
	Route::get('/quienes-somos', 'Frontend\PaginasController@empresa');
	Route::get('/nuestros-clientes', 'Frontend\PaginasController@nuestrosClientes');
	Route::get('/servicios', 'Frontend\PaginasController@servicios');
	Route::get('/productos', 'Frontend\PaginasController@productos');
	Route::get('/noticias', 'Frontend\PaginasController@noticias');
	Route::get('/noticias/{slug}', 'Frontend\PaginasController@articulo');
	Route::get('/certificaciones', 'Frontend\PaginasController@certificaciones');
	Route::get('/contactos', 'Frontend\PaginasController@contactos');
	Route::get('/productos/{id}', 'Frontend\PaginasController@producto');
	Route::post('/enviarmensaje',	'Frontend\PaginasController@enviarmensaje')->name('paginas.enviarmensaje');
// Fin de las rutas de las paginas informativas

// Carrito de compra
	Route::resource('cart', 'Frontend\CartsController');
	Route::post('cart/addProducto/{id}', 'Frontend\CartsController@addProducto');
	Route::post('cart/guardarPedido', 'Frontend\CartsController@guardarPedido');
	Route::post('cart/ingresar-pago', 'Frontend\CartsController@pagos');
	Route::post('save-deposito', 'Frontend\CartsController@subirDocumento');
// Fin carrito

// Lista de deseados
	Route::resource('wishlist', 'Frontend\WishlistController');
// Fin lista de deseados

// Rutas para los Cliente
	Route::prefix('cliente')->group(function () {

// Rutas de login de los clientes 
	Route::get('login', 'Auth\ClienteLoginController@login')->name('cliente.auth.login');
	Route::post('login', 'Auth\ClienteLoginController@loginCliente')->name('cliente.auth.loginCliente');
	Route::post('logout', 'Auth\ClienteLoginController@logout')->name('cliente.auth.logout');

	Route::get('redirect/{provider}', 'Auth\ClienteLoginController@redirectToProvider')->name('loginSocial');
	Route::get('callback/{provider}', 'Auth\ClienteLoginController@handleProviderCallback');
// Fin de rutas de login clientes

// Panel de adminstraccion del cliente
	Route::get('/', 'Frontend\ClienteController@index')->name('cliente.dashboard');
	Route::get('dashboard', 'Frontend\ClienteController@index')->name('cliente.dashboard');
	Route::get('mis-pedidos', 'Frontend\ClienteController@misPedidos')->name('cliente.misPedidos');
	Route::post('cancelar-pedido', 'Frontend\ClienteController@cancelarPedido');
	Route::get('ofertas', 'Frontend\ClienteController@ofertas')->name('cliente.getOfertas');
	Route::get('deseados', 'Frontend\ClienteController@deseados')->name('cliente.misDeseos');
	Route::get('miperfil', 'Frontend\ClienteController@miPerfil')->name('cliente.miPerfil');
	Route::post('actualizar-perfil', 'Frontend\ClienteController@guardarPerfil');
	Route::post('save-direccion', 'Frontend\ClienteController@guardarDireccion');
	Route::get('show-direccion/{id}', 'Frontend\ClienteController@mostrarDireccion');
	Route::get('delete-direccion/{id}', 'Frontend\ClienteController@eliminarDireccion');
	Route::get('register', 'Frontend\ClienteController@create')->name('cliente.register');
	Route::post('register', 'Frontend\ClienteController@store')->name('cliente.register.store');
// Fin del panel de adminstracion del cliente

// Rutas para el pago de compra  
	Route::get('saveCard', 'Frontend\CartsController@saveCard')->name('saveCard');
	Route::get('checkout/{id}', 'Frontend\CartsController@formPago')->name('checkout');
	Route::post('checkout-save', 'Frontend\CartsController@formSave')->name('checkoutSave');
	Route::get('pagar-pedido/{id}', 'Frontend\CartsController@pagar');
	Route::get('estado-pago/{code}/{orden}', 'Frontend\CartsController@estadoPago');
	Route::get('getcupon/{id}/{cupon}','Frontend\CartsController@agregarCupon');
// Fin del carrito de comprar

// Rutas para recuperar contraseña
	Route::get('password/reset', 'Auth\ClienteForgotPasswordController@showLinkRequestForm')->name('cliente.password.request');
	Route::post('password/email', 'Auth\ClienteForgotPasswordController@sendResetLinkEmail')->name('cliente.password.email');

});
// Fin de rutas clientes
/* Fin Rutas Frontend */



/* Inicio Backend */

// Rutas de login Administrador
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');

// Password Reset Routes Administrador
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::group(['middleware' => ['auth']], function(){

	Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

	// Rutas inicialiales
	Route::get('/home', 'Backend\HomeController@index')->name('home');
	Route::get('/administracion', 'Backend\BackendController@index');
	// fin de las rutas iniciales

	// Inicio de adminsitracion de usuaruios
	Route::resource('usuarios','Backend\UsuariosController');
	Route::get('/perfil', 'Backend\UsuariosController@perfil')->name('perfil');
	Route::resource('tipos-usuarios','Backend\TiposController');
	Route::resource('menu', 'Backend\MenuController');
	Route::resource('permisos', 'Backend\PermisoController');
	// Fin de administracion de usuarios 

	// Inicio de administracion de clientes
	Route::resource('clientes', 'Backend\ClientesController');
	Route::get('saldo-cliente', 'Backend\ClientesController@saldoCliente');
	Route::resource('menu-pagina', 'Backend\MenuPaginaController');
	// fin administracion de clientes

	// Inicio  de administracion de contenido
	Route::resource('articulos', 'Backend\ArticulosController');
	Route::post('/upload', 'Backend\ArticulosController@subirfotogaleria');
	Route::post('/uploaddoc', 'Backend\ArticulosController@subirdoc');
	Route::get('/activaciones','Backend\ArticulosController@activaciones');
	Route::post('/activararticulo/{id}', 'Backend\ArticulosController@habilitArarticulo')->name('hab_articulo');
	Route::resource('categorias','Backend\CategoriasController');
	Route::resource('tags', 'Backend\TagsController');
	Route::post('/getTags/{id}', 'Backend\TagsController@getTagsByCategoria');
	// Fin de adminsitracion de contenido

	// Administracion de carrito
		Route::resource('carrito', 'Backend\CarritoController');
		Route::post('carrito/save-politica', 'Backend\CarritoController@subirDocumento');
		Route::resource('cupones','Backend\CuponController');
		Route::resource('pedidos', 'Backend\PedidosController');
		Route::resource('depositos', 'Backend\DepositosController');
	// Fin administracion de carrito

	// Administracion Productos
		Route::resource('shop','Backend\TiendaController');
		Route::post('/upfoto', 'Backend\TiendaController@subirfotogaleria');
		Route::resource('categoriaproductos','Backend\CategoriaproductosController');
		Route::post('/getCproductos/{id}', 'Backend\CategoriaproductosController@getCproductos');
	// Fin administracion de productos	

	//Inicio Modulos
		Route::resource('categoriainterna','Backend\CategoriaInternaController');
		Route::resource('animacion', 'Backend\SliderController');
		Route::resource('imagen', 'Backend\ImagenesController');
		Route::resource('video', 'Backend\VideoController');
	//Fin Modulos

	// Rutas Administracion
		Route::resource('/informacion', 'Backend\InformacionController');
		Route::resource('configuracion', 'Backend\ConfiguracionController');
	// Fin Rutas administracion

	// Inicio de campos extras
		Route::resource('camposextrasgrupos','Backend\CamposExtrasGruposController');
		Route::resource('camposextras','Backend\CamposExtrasController');
	// Fin Campos extras 

	// Inicio cursos
		Route::resource('cursos', 'Backend\CursosController');
		Route::post('cursos/filtrar', 'Backend\CursosController@filtrar');
		Route::get('modulos-articulo/{id}', 'Backend\CursosController@ModulosArticulo');

		Route::resource('modulo', 'Backend\ModuloController');
	// Fin cursos 

	// Inicio documentos
		Route::post('upload-image', 'UploadController@upload_image');
		Route::post('upload-file', 'UploadController@upload_file');
	// Fin documentos

	// Rutas que no se usan
	Route::resource('galeria', 'FotosController');
	Route::resource('especificaciones', 'EspecificacionController');
	//Route::post('/enviarconsulta',	'Frontend\PaginasController@enviarconsulta')->name('paginas.enviarconsulta');
	//Route::get('/etiqueta/{tag}',	'Frontend\PaginasController@tags')->name('Tags');
	//Route::get('/galeria/{slug}',	'Frontend\PaginasController@galeria')->name('galeria');
	//Route::get('/infoevento', 		'Frontend\PaginasController@infoeventos');
	//Route::get('/proyectos/{slug}', 'Frontend\PaginasController@articulo')->name('proyectos.slug');
	//Route::get('/email', 			'Frontend\PaginasController@email')->name('email');
	//Route::get('/apinoticia',		'ApiNoticiasController@api')->name('apinoticia');
	//Antiguo FUNCIONA Route::get('/noticia', 'ApiNoticiasController@noticia')->name('noticia');	

});

local/app/Video.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Video extends Model
{
    //
     protected $table = 'videos';

    protected $fillable = ['titulo', 'path','descripcion','orden','id_categoriainterna'];

 	protected $hidden = [];
}

local/app/Http/Controllers/Backend/VideoController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Video;
use View;
use Session;
use Redirect;
use Illuminate\Support\Facades\DB;
use App\CategoriaInterna;
use App\Http\Requests\VideoActualizarRequest;
use App\Http\Requests\VideoCrearRequest;

class VideoController extends Controller
{
    

     public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
      

         $videos = DB::table("videos")
                ->join("categoriainterna","videos.id_categoriainterna","=","categoriainterna.id")
                ->select("videos.*","categoriainterna.nombre")
                ->get();

        
        return View::make('admin.video.index', compact('videos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $categorias = CategoriaInterna::pluck('nombre','id');
      
         return View::make('admin.video.crear' , compact('categorias'));
         
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(VideoCrearRequest $request)
    {
        //
        $video = new Video($request->all());
        
        $video->save();
        Session::flash('message','Video guardada correctamente');
        return redirect::to('video');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
         $video= Video::find($id);
         $categorias = CategoriaInterna::pluck('nombre','id');
       return view('admin.video.editar',compact('video','categorias'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(VideoActualizarRequest $request, $id)
    {
        //
          $video= Video::find($id);
         $video->fill($request->all());
         $video->save();

         Session::flash('message','Video actualizada correctamente');
         return redirect::to('video');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         Video::find($id)->delete();
        
         Session::flash('message','Video eliminada correctamente');
         return Redirect::route('video.index');
    }
}

local/resources/views/admin/video/crear.blade.php
@extends('layouts.backend')
@section('titulo', 'Nuevo video')
@section('contenido')
    
    @include('alerts.request')

    <div class="row">
        
        <div class="col-md-6">  
            {!! Form::open(['route' => 'video.store', 'method' => 'POST']) !!}
                <div class="form-group">
                    {!! Form::label('titulo','Título') !!}
                    {!! Form::text('titulo',null,['class' =>'form-control', 'placeholder' =>'Título del artículo','required'])!!}
                </div>
                <div class="form-group">
                    {!! Form::label('descripcion', 'Descripcion:') !!}
                    {!! Form::text('descripcion',null,['class'=>'form-control','placeholder'=>'Descripción del Slider','required']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('categoria','Categoria') !!}
                    {!! Form::select('id_categoriainterna',$categorias, null,[ 'class' =>'form-control','required' , 'list' =>'listas'])!!}
                </div>
                <div class="form-group">
                    {!! Form::label('path','URL del Video de Youtube') !!}
                    {!! Form::text('path',null,['class' =>'form-control', 'placeholder' =>'Pegue aquí la URL del video','required'])!!}
                </div>
               <div class="form-group">
                    {!! Form::button('<i class="fa fa-save"></i> Guardar', ['class' =>'btn btn-primary', 'type'=>'submit']) !!}
                    <a href="{{ route('video.index') }}" class="btn btn-warning"><i class="fa fa-chevron-left"></i> Regresar</a>
                </div>
            {!! Form::close() !!}
        </div>
        <div class="clearfix"></div>
    </div>
    
@endsection

local/resources/views/admin/video/editar.blade.php
@extends('layouts.backend')
@section('titulo', 'Editar')
@section('contenido')
    @include('alerts.request')
    <div class="row">
        
        <div class="col-md-6">  
            {!! Form::model($video, array('method' => 'PATCH', 'route' => array('video.update', $video->id) , 'files' => true)) !!}
                <div class="form-group">
                    {!! Form::label('titulo','Título') !!}
                    {!! Form::text('titulo',null,['class' =>'form-control', 'placeholder' =>'Título del artículo','required'])!!}
                </div>
                <div class="form-group">
                    {!! Form::label('descripcion', 'Descripcion:') !!}
                    {!! Form::text('descripcion',null,['class'=>'form-control','placeholder'=>'Descripción de la imagen']) !!}
                </div>
                <div class="form-group">
                    {!! Form::label('categoriainterna','Categoria') !!}
                    {!! Form::select('id_categoriainterna',$categorias, null,[ 'class' =>'form-control' , 'list' =>'listas'])!!}
                </div>
                <div class="form-group">
                    {!! Form::label('path','URL del Video de YouTuBe') !!}
                    {!! Form::text('path',null,['class' =>'form-control', 'placeholder' =>'Pegue aquí la URL del video','required'])!!}
                </div>
               <div class="form-group">
                    {!! Form::button('<i class="fa fa-save"></i> Actualizar', ['class' =>'btn btn-primary', 'type'=>'submit']) !!}
                    <a href="{{ route('video.index') }}" class="btn btn-warning"><i class="fa fa-chevron-left"></i> Regresar</a>
                </div>
            {!! Form::close() !!}
        </div>
        <div class="clearfix"></div>
    </div>
    
@stop

local/resources/views/admin/video/index.blade.php
@extends('layouts.backend')

@section('titulo')
<div style="display: flex;justify-content: center;align-items: center;">
    <p style="margin-right: 30px; margin-bottom: 0px;">Videos</p>
    <a class="btn btn-primary btn_crear" href="{{ URL::route('video.create') }}">Nuevo</a>
</div>
@endsection
@section('contenido')
    @include('alerts.success')
    <!-- <a class="btn btn-primary" href="{{ URL::route('video.create') }}">Nuevo</a> -->
    @if (count($videos))
        <table id="tbbuzon" class="table table-striped table-bordered table-hover display" >
            <thead>
                <tr>
                    
                    <th>Título</th>
                    <th>Descrición</th>
                    <th>Categoria</th>
                    <th>URL</th>            
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($videos as $video)
                <tr>
                    <td>{{$video->titulo}}</td>
                    <td>{{ $video->descripcion }}</td>
                    <td>{{ $video->nombre }}</td>
                    <td><a href="#" onclick="openVideoModal('{{ $video->path }}')">{{ $video->path }}</a></td>
                    <td><a class="btn btn-success" href="{{route('video.edit', $video->id)}}" role="button"><i class="fa fa-pencil-square-o"></i></a>
                    {!! Form::open(array('method' => 'DELETE', 'route' => array('video.destroy', $video->id))) !!}
                        <button type="submit" onclick="return confirm('Quiere borrar el registro?')" class="btn btn-danger"><span class="fa fa-trash-o"></span></button>
                    {!! Form::close() !!}
                </td>
            </tr>
            @endforeach
            
        </tbody>

        </table>

        <div class="modal fade" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="videoModal" aria-hidden="true">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-body">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <div class="embed-responsive embed-responsive-16by9">
                            <iframe class="embed-responsive-item" width="100%" height="350" src=""></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @else
        <div class="alert alert-warning " role="alert">
            No existen videos actualmente, empecemos creando uno <a href="{{ route('video.create') }}">aqui</a>
        </div>
    @endif
    <style type="text/css">
        .modal-dialog {
            max-width: 800px;
            margin: 30px auto;
        }
        .modal-body {
            position:relative;
            padding:0px;
        }
        .close {
            position:absolute;
            right:-30px;
            top:0;
            z-index:999;
            font-size:2rem;
            font-weight: normal;
            color:#fff;
            opacity:1;
        }
    </style>
    <script type="text/javascript">

        function openVideoModal(url){
            link = ''
            if (url.indexOf("youtube.com") != -1) {
                link = url.substr(url.indexOf("?v=")+3,11);
            }else if(url.indexOf("youtu.be/") != -1) {
                link = url.substr(url.indexOf("be")+3,11);
            }
            link = (link != '' ? '//www.youtube.com/embed/'+link : url );
            $("#videoModal iframe").attr("src", link + '?modestbranding=1&showinfo=0');
            $('#videoModal').modal('show');
        }

        $("#videoModal").on('hidden.bs.modal', function (e) {
            $("#videoModal iframe").attr("src", '');
        });
    </script>
@endsection