local/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/* Rutas Frontend */ 
// Rutas de las paginas Informativas
	Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
	//Route::get('/', 'Frontend\PaginasController@index')->name('inicio');
	Route::get('/categoria/{id}', 'Frontend\PaginasController@categoria');
	Route::get('/producto/{id}', 'Frontend\PaginasController@producto');
	Route::post('/mostrardatosproducto',	'Frontend\PaginasController@mostrardatosproducto')->name('producto.mostrardatosproducto');
	Route::get('/quienes-somos', 'Frontend\PaginasController@empresa');
	Route::get('/nuestros-clientes', 'Frontend\PaginasController@nuestrosClientes');
	Route::get('/servicios', 'Frontend\PaginasController@servicios');
	Route::get('/productos', 'Frontend\PaginasController@productos');
	Route::get('/noticias', 'Frontend\PaginasController@noticias');
	Route::get('/noticias/{slug}', 'Frontend\PaginasController@articulo');
	Route::get('/certificaciones', 'Frontend\PaginasController@certificaciones');
	Route::get('/contactos', 'Frontend\PaginasController@contactos');
	Route::get('/productos/{id}', 'Frontend\PaginasController@producto');
	Route::post('/enviarmensaje',	'Frontend\PaginasController@enviarmensaje')->name('paginas.enviarmensaje');
// Fin de las rutas de las paginas informativas

// Carrito de compra
	Route::resource('cart', 'Frontend\CartsController');
	Route::post('cart/addProducto/{id}', 'Frontend\CartsController@addProducto');
	Route::post('cart/guardarPedido', 'Frontend\CartsController@guardarPedido');
	Route::post('cart/ingresar-pago', 'Frontend\CartsController@pagos');
	Route::post('save-deposito', 'Frontend\CartsController@subirDocumento');
// Fin carrito

// Lista de deseados
	Route::resource('wishlist', 'Frontend\WishlistController');
// Fin lista de deseados

// Rutas para los Cliente
	Route::prefix('cliente')->group(function () {

// Rutas de login de los clientes 
	Route::get('login', 'Auth\ClienteLoginController@login')->name('cliente.auth.login');
	Route::post('login', 'Auth\ClienteLoginController@loginCliente')->name('cliente.auth.loginCliente');
	Route::post('logout', 'Auth\ClienteLoginController@logout')->name('cliente.auth.logout');

	Route::get('redirect/{provider}', 'Auth\ClienteLoginController@redirectToProvider')->name('loginSocial');
	Route::get('callback/{provider}', 'Auth\ClienteLoginController@handleProviderCallback');
// Fin de rutas de login clientes

// Panel de adminstraccion del cliente
	Route::get('/', 'Frontend\ClienteController@index')->name('cliente.dashboard');
	Route::get('dashboard', 'Frontend\ClienteController@index')->name('cliente.dashboard');
	Route::get('mis-pedidos', 'Frontend\ClienteController@misPedidos')->name('cliente.misPedidos');
	Route::post('cancelar-pedido', 'Frontend\ClienteController@cancelarPedido');
	Route::get('ofertas', 'Frontend\ClienteController@ofertas')->name('cliente.getOfertas');
	Route::get('deseados', 'Frontend\ClienteController@deseados')->name('cliente.misDeseos');
	Route::get('miperfil', 'Frontend\ClienteController@miPerfil')->name('cliente.miPerfil');
	Route::post('actualizar-perfil', 'Frontend\ClienteController@guardarPerfil');
	Route::post('save-direccion', 'Frontend\ClienteController@guardarDireccion');
	Route::get('show-direccion/{id}', 'Frontend\ClienteController@mostrarDireccion');
	Route::get('delete-direccion/{id}', 'Frontend\ClienteController@eliminarDireccion');
	Route::get('register', 'Frontend\ClienteController@create')->name('cliente.register');
	Route::post('register', 'Frontend\ClienteController@store')->name('cliente.register.store');
// Fin del panel de adminstracion del cliente

// Rutas para el pago de compra  
	Route::get('saveCard', 'Frontend\CartsController@saveCard')->name('saveCard');
	Route::get('checkout/{id}', 'Frontend\CartsController@formPago')->name('checkout');
	Route::post('checkout-save', 'Frontend\CartsController@formSave')->name('checkoutSave');
	Route::get('pagar-pedido/{id}', 'Frontend\CartsController@pagar');
	Route::get('estado-pago/{code}/{orden}', 'Frontend\CartsController@estadoPago');
	Route::get('getcupon/{id}/{cupon}','Frontend\CartsController@agregarCupon');
// Fin del carrito de comprar

// Rutas para recuperar contraseña
	Route::get('password/reset', 'Auth\ClienteForgotPasswordController@showLinkRequestForm')->name('cliente.password.request');
	Route::post('password/email', 'Auth\ClienteForgotPasswordController@sendResetLinkEmail')->name('cliente.password.email');

});
// Fin de rutas clientes
/* Fin Rutas Frontend */



/* Inicio Backend */

// Rutas de login Administrador
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');

// Password Reset Routes Administrador
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::group(['middleware' => ['auth']], function(){

	Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

	// Rutas inicialiales
	Route::get('/home', 'Backend\HomeController@index')->name('home');
	Route::get('/administracion', 'Backend\BackendController@index');
	// fin de las rutas iniciales

	// Inicio de adminsitracion de usuaruios
	Route::resource('usuarios','Backend\UsuariosController');
	Route::get('/perfil', 'Backend\UsuariosController@perfil')->name('perfil');
	Route::resource('tipos-usuarios','Backend\TiposController');
	Route::resource('menu', 'Backend\MenuController');
	Route::resource('permisos', 'Backend\PermisoController');
	// Fin de administracion de usuarios 

	// Inicio de administracion de clientes
	Route::resource('clientes', 'Backend\ClientesController');
	Route::get('saldo-cliente', 'Backend\ClientesController@saldoCliente');
	Route::resource('menu-pagina', 'Backend\MenuPaginaController');
	// fin administracion de clientes

	// Inicio  de administracion de contenido
	Route::resource('articulos', 'Backend\ArticulosController');
	Route::post('/upload', 'Backend\ArticulosController@subirfotogaleria');
	Route::post('/uploaddoc', 'Backend\ArticulosController@subirdoc');
	Route::get('/activaciones','Backend\ArticulosController@activaciones');
	Route::post('/activararticulo/{id}', 'Backend\ArticulosController@habilitArarticulo')->name('hab_articulo');
	Route::resource('categorias','Backend\CategoriasController');
	Route::resource('tags', 'Backend\TagsController');
	Route::post('/getTags/{id}', 'Backend\TagsController@getTagsByCategoria');
	// Fin de adminsitracion de contenido

	// Administracion de carrito
		Route::resource('carrito', 'Backend\CarritoController');
		Route::post('carrito/save-politica', 'Backend\CarritoController@subirDocumento');
		Route::resource('cupones','Backend\CuponController');
		Route::resource('pedidos', 'Backend\PedidosController');
		Route::resource('depositos', 'Backend\DepositosController');
	// Fin administracion de carrito

	// Administracion Productos
		Route::resource('shop','Backend\TiendaController');
		Route::post('/upfoto', 'Backend\TiendaController@subirfotogaleria');
		Route::resource('categoriaproductos','Backend\CategoriaproductosController');
		Route::post('/getCproductos/{id}', 'Backend\CategoriaproductosController@getCproductos');
	// Fin administracion de productos	

	//Inicio Modulos
		Route::resource('categoriainterna','Backend\CategoriaInternaController');
		Route::resource('animacion', 'Backend\SliderController');
		Route::resource('imagen', 'Backend\ImagenesController');
		Route::resource('video', 'Backend\VideoController');
	//Fin Modulos

	// Rutas Administracion
		Route::resource('/informacion', 'Backend\InformacionController');
		Route::resource('configuracion', 'Backend\ConfiguracionController');
	// Fin Rutas administracion

	// Inicio de campos extras
		Route::resource('camposextrasgrupos','Backend\CamposExtrasGruposController');
		Route::resource('camposextras','Backend\CamposExtrasController');
	// Fin Campos extras 

	// Inicio cursos
		Route::resource('cursos', 'Backend\CursosController');
		Route::post('cursos/filtrar', 'Backend\CursosController@filtrar');
		Route::get('modulos-articulo/{id}', 'Backend\CursosController@ModulosArticulo');

		Route::resource('modulo', 'Backend\ModuloController');
	// Fin cursos 

	// Inicio documentos
		Route::post('upload-image', 'UploadController@upload_image');
		Route::post('upload-file', 'UploadController@upload_file');
	// Fin documentos

	// Rutas que no se usan
	Route::resource('galeria', 'FotosController');
	Route::resource('especificaciones', 'EspecificacionController');
	//Route::post('/enviarconsulta',	'Frontend\PaginasController@enviarconsulta')->name('paginas.enviarconsulta');
	//Route::get('/etiqueta/{tag}',	'Frontend\PaginasController@tags')->name('Tags');
	//Route::get('/galeria/{slug}',	'Frontend\PaginasController@galeria')->name('galeria');
	//Route::get('/infoevento', 		'Frontend\PaginasController@infoeventos');
	//Route::get('/proyectos/{slug}', 'Frontend\PaginasController@articulo')->name('proyectos.slug');
	//Route::get('/email', 			'Frontend\PaginasController@email')->name('email');
	//Route::get('/apinoticia',		'ApiNoticiasController@api')->name('apinoticia');
	//Antiguo FUNCIONA Route::get('/noticia', 'ApiNoticiasController@noticia')->name('noticia');	

});

local/app/CategoriaInterna.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CategoriaInterna extends Model
{
    //
    protected $table = 'categoriainterna';
    protected $primarykey='id';

  protected $fillable = ['nombre','descripcion','patch','updated_at', 'created_at'];

  protected $hidden = [];


}

local/app/Http/Controllers/Backend/CategoriaInternaController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Requests\CategoriaInternaCrearRequest;
use App\Http\Requests\CategoriaInternaModificarRequest;
use App\Http\Controllers\Controller;
use App\CategoriaInterna;
use View;
use Auth;
use Session;
use Redirect;
use Illuminate\Support\Facades\DB;
use App\funcionesgestor;

use Illuminate\Support\Facades\Input;
//include('app.func');
//include(app_path() . '\funcionesgestor.php');

class CategoriaInternaController extends Controller
{
    //


     function limpiar_caracteres_especiales($s) {
      $s = str_replace("á","a",$s);
      $s = str_replace("Á","A",$s);
      $s = str_replace("é","e",$s);
      $s = str_replace("É","E",$s);
      $s = str_replace("í","i",$s);
      $s = str_replace("Í","I",$s);
      $s = str_replace("ó","o",$s);
      $s = str_replace("Ó","O",$s);
      $s = str_replace("ú","u",$s);
      $s = str_replace("Ú","U",$s);
      $s = str_replace(" ","-",$s);
      $s = str_replace("´","-",$s);
      $s = str_replace("ñ","n",$s);
      $s = str_replace("Ñ","N",$s);
      //para ampliar los caracteres a reemplazar agregar lineas de este tipo:
      //$s = str_replace("caracter-que-queremos-cambiar","caracter-por-el-cual-lo-vamos-a-cambiar",$s);
      return $s;
    }

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
       $categorias = CategoriaInterna::orderBy('id','DESC')->paginate(50);
        return view('admin.categoriainterna.index', compact('categorias'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('admin.categoriainterna.crear');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoriaInternaCrearRequest $request)
    {
        // dd($request->all());
        $categoria = new CategoriaInterna($request->all());
        
        ////////////////////////////////// imagenprincipalcategoria
            $imagen = $request->path;
            

            $dir = public_path().'/imagescat/';

           	$docs = $request->file('path');
            
            // dd($icono);
            // dd($docs);

            if (Input::hasFile('path')){

                $imagen = $docs->getClientOriginalName();
                $imagen = $this->limpiar_caracteres_especiales($imagen);
                //dd($imagenprincipal);
                $docs->move($dir, $imagen);
            }

            

        /////////////////////////
            
        $categoria->path = $imagen;
        
        $categoria->nombre = $request->nombre;  
        $categoria->descripcion = $request->descripcion;  
        
        $categoria->save();

        Session::flash('message','Categoria fue creada correctamente');
        return redirect::to('categoriainterna');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       $categoria= CategoriaInterna::find($id);
       return view('admin.categoriainterna.editar',compact('categoria'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoriaInternaModificarRequest $request, $id)
    {
         // dd($request->all());
         $categoria= CategoriaInterna::find($id);
         $categoria->fill($request->all());
         ////////////////////////////////// imagenprincipalcategoria

            $imagenprincipal = $categoria->path;
            $nombreicono = $categoria->icono;

            $dir = public_path().'/imagescat/';

            $docs = $request->file('path');
            
            // dd($docs);

            if (Input::hasFile('path')){

                $imagenprincipal = $docs->getClientOriginalName();
                $imagenprincipal = $this->limpiar_caracteres_especiales($imagenprincipal);
                //dd($imagenprincipal);
                $docs->move($dir, $imagenprincipal);
            }

            

        /////////////////////////

         $categoria->path = $imagenprincipal;
         $categoria->nombre = $request->nombre;  
         $categoria->descripcion = $request->descripcion;
         $categoria->save();

         Session::flash('message','Categoria actualizada correctamente');
        return redirect::to('categoriainterna');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        CategoriaInterna::find($id)->delete();
        

        Session::flash('message','Categoria eliminada correctamente');
        return Redirect::route('categoriainterna.index');
      
    }

}

local/resources/views/admin/categoriainterna/crear.blade.php
@extends('layouts.backend')
@section('titulo')
Nueva Categoria
@stop
@section('contenido')
           {!! Form::open(['route' => 'categoriainterna.store', 'method' => 'POST',
           					'files'=>true]) !!}
				<div class="form-group">
					{!! Form::label('nombre','Nombre de Categoria') !!}
					{!! Form::text('nombre',null,['class' =>'form-control', 'placeholder' =>'Ingrese nombre de categoria','required'])!!}
				</div>
				<div class="form-group">
					{!! Form::label('descripcion','Descrición') !!}
					{!! Form::text('descripcion',null,['class' =>'form-control', 'placeholder' =>'Ingrese Descripción','required'])!!}
			</div>
			<div class="form-group"  >
						{!! Form::label('path','Imagen Categoria') !!}
						{!! Form::file('path',[])!!}
				</div>
				<div class="form-group">
					{!! Form::submit('Registrar', ['class' =>'btn btn-primary btn_formc']) !!}
				</div>
			{!! Form::close() !!}
@endsection			

local/resources/views/admin/categoriainterna/editar.blade.php
@extends('layouts.backend')
@section('titulo')
Editar
@stop
@section('contenido')
@if(count($errors) >0)
<div class="alert alert-danger" role="alert">
  <ul>
  	@foreach($errors->all() as $error)
  	<li>{{$error}}</li>
  	@endforeach
  </ul>
</div>
@endif
{!!Form::model($categoria,['route'=>['categoriainterna.update',$categoria],'method'=>'PUT','files' => true])!!}
			<div class="form-group"  >
				<div class="col-md-2">
					<img src="{{asset('local/public/images')}}/{{$categoria->path}}" onerror="if (this.src != '../../local/public/images/avatar.png') this.src = '../../local/public/images/avatar.png';"  style ="width: 100px">
				</div>
		       	<div class="col-md-10">
						{!! Form::label('path','Imagen Categoria') !!}
						{!! Form::file('path',[])!!}
				</div>
				<div style="clear: both;"></div>
			</div>
          	<div class="form-group">
          			{!! Form::label('nombre', 'Nombre de categoria:') !!}
                    {!! Form::text('nombre',null,['class'=>'form-control','placeholder'=>'Ingrese nombre','required']) !!}
	       </div>
	       <div class="form-group">
					{!! Form::label('descripcion','Descripción de Categoria') !!}
					{!! Form::text('descripcion',null,['class' =>'form-control', 'placeholder' =>'Descripción de categoria','required'])!!}
			</div>
			<div class="form-group">
				{!! Form::submit('Actualizar', ['class' =>'btn btn-primary btn_formc']) !!}
			</div>
			{!! Form::close() !!}
@endsection			

local/resources/views/admin/categoriainterna/index.blade.php
@extends('layouts.backend')
@section('titulo')
<div style="display: flex;justify-content: center;align-items: center;">
    <p style="margin-right: 30px; margin-bottom: 0px;">Categorías</p>
    <a class="btn btn-primary btn_crear" href="{{ URL::route('categoriainterna.create') }}">Nuevo</a>
</div>
@endsection
@section('contenido')
@if(Session::has('message'))
<div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  {{Session::get('message')}}
</div>
@endif
<!-- <a class="btn btn-primary" href="{{ URL::route('categoriainterna.create') }}">Nuevo</a>
<br> -->
@if ($categorias->count())
<br>
    <div class="row">
      <div class="col-md-12">  
<table  id="tbbuzon" class="table table-striped table-bordered table-hover display" >
  <thead>
    <th>Nombre de categorías</th>
    <th>Descripción</th>
    <th>Imagen</th>
    <th>Acciones</th>
  </thead>
  <tbody>
    <tr>
      @foreach ($categorias as $categoria)
      <td>{{$categoria->nombre}}</td>
      <td>{{$categoria->descripcion}}</td>
      @if(empty($categoria->path))
                  <td><img src="{{asset('assets/images')}}/no-imagen.jpg"  style ="width: 50px; height: 50px!important;object-fit: cover!important;"></td>
                @else
                  <td>
                     <div class="lightBoxGallery">
                            <a href="{{asset('local/public/imagescat')}}/{{$categoria->path}}" title="Image from Unsplash" data-gallery="">
                              <img  style="width: 50px;height: 50px!important;"  src="{{asset('local/public/imagescat')}}/{{$categoria->path}}">
                            </a>
                            <!-- The Gallery as lightbox dialog, should be a child element of the document body -->
                            <div id="blueimp-gallery" class="blueimp-gallery">
                                <div class="slides"></div>
                                <h3 class="title"></h3>
                                <a class="prev">‹</a>
                                <a class="next">›</a>
                                <a class="close">×</a>
                                <a class="play-pause"></a>
                                <ol class="indicator"></ol>
                            </div>
                        </div>
                  </td>
                @endif
      <td><a class="btn btn-success" href="{{route('categoriainterna.edit', $categoria->id)}}" role="button"><i class="fa fa-pencil-square-o"></i></a>
        {!! Form::open(array('method' => 'DELETE', 'route' => array('categoriainterna.destroy', $categoria->id))) !!}
          <button type="submit" onclick="return confirm('Quiere borrar el registro?')" class="btn btn-danger"><span class="fa fa-trash"></span></button>
        {!! Form::close() !!}
          
      </td>
    </tr>
    @endforeach
  </tbody>
</table>
   </div>
      <div class="col-md-6">
      </div>
    </div>
@else
    No hay Categorias
@endif
{!! $categorias->render() !!}
@endsection